from __future__ import annotations

from .db_connection import DBClient, connect, get_database_url, get_db_path
from .db_operations import (
    add_message,
    ensure_user_settings,
    create_memory_item,
    create_user_model_config,
    create_session,
    create_user,
    create_user_persona,
    ensure_default_persona_for_user,
    ensure_user_exists,
    find_user_by_email,
    find_user_by_id,
    get_active_model_for_user,
    get_latest_chat_summary,
    get_model_config_by_id_for_user,
    get_or_create_session_for_user,
    get_selected_persona_for_user,
    get_session,
    get_user_ai_selection,
    get_user_settings,
    list_recent_messages,
    list_memory_items,
    list_user_model_configs,
    list_user_personas,
    now_iso,
    rebuild_chat_summary,
    select_user_persona,
    set_user_ai_selection,
    update_user_persona,
    update_user_model_config,
)
from .db_schema import init_db

__all__ = [
    "DBClient",
    "add_message",
    "connect",
    "ensure_user_settings",
    "create_memory_item",
    "create_user_model_config",
    "create_session",
    "create_user",
    "create_user_persona",
    "ensure_default_persona_for_user",
    "ensure_user_exists",
    "find_user_by_email",
    "find_user_by_id",
    "get_database_url",
    "get_db_path",
    "get_active_model_for_user",
    "get_latest_chat_summary",
    "get_model_config_by_id_for_user",
    "get_or_create_session_for_user",
    "get_selected_persona_for_user",
    "get_session",
    "get_user_ai_selection",
    "get_user_settings",
    "list_recent_messages",
    "list_memory_items",
    "list_user_model_configs",
    "list_user_personas",
    "init_db",
    "now_iso",
    "rebuild_chat_summary",
    "select_user_persona",
    "set_user_ai_selection",
    "update_user_persona",
    "update_user_model_config",
]
